### PR TITLE
Convert the sample apps to explicit int comparisons

### LINKED ISSUE #131: Current sample apps don't compile
On the latest main branch, both the cat and crc32 sample programs fail with the following error: `Condition must be a boolean expression`.

To prevent this in the future, it might be a good idea to add these to `cargo test`.

## Cat

For the cat example, compilation fails because of the following line:
```jakt
20:    while not feof(file) {
```

Since feof returns a c_int and while expects a boolean. Changing the condition to `feof(file) == 0` does not work as comparisons between `c_int` and normal numeric types is not supported.

## CRC

For the crc example, the incorrect line is the following:
```jakt
14:    if value & 1 {
```

Here, `value & 1` does not result in a boolean value. Replacing this with `value & 1 != 0` would solve the problem but that again needs the `c_int` and numeric comparisons.

### PR DESCRIPTION
**Pull request by HectorPeeters**
- Change the sample apps to use explicit `c_int` comparisons instead of relying on an implicit cast which is not implemented at the moment
- Add support for `c_int` types in numeric compare expressions
- Make `make_lookup_table` throws (see #137)

Closes #131

### CODE REVIEW

File: src/typechecker.rs [hunk 1]
```diff
@@ -54,8 +54,10 @@ pub fn can_fit_integer(type_id: TypeId, value: &IntegerConstant) -> bool {
     match *value {
         IntegerConstant::Signed(value) => match type_id {
             I8_TYPE_ID => value >= i8::MIN as i64 && value <= i8::MAX as i64,
+            CCHAR_TYPE_ID => value >= i8::MIN as i64 && value <= i8::MAX as i64,
             I16_TYPE_ID => value >= i16::MIN as i64 && value <= i16::MAX as i64,
             I32_TYPE_ID => value >= i32::MIN as i64 && value <= i32::MAX as i64,
+            CINT_TYPE_ID => value >= i32::MIN as i64 && value <= i32::MAX as i64,
```
Comment (linusg) [inline src/typechecker.rs:60]: - Let's put these at the top and next to each other, like in `is_integer
- Pretty sure we should be using `https://doc.rust-lang.org/std/os/raw/type.c_int.html` (and `c_char`) for MIN and MAX here, they're not guaranteed to be i8 and i32 on all platforms and architectures

File: src/typechecker.rs [hunk 2]
```diff
@@ -453,8 +455,10 @@ impl IntegerConstant {
         let new_constant = match self {
             IntegerConstant::Signed(value) => match type_id {
                 I8_TYPE_ID => NumericConstant::I8(*value as i8),
+                CCHAR_TYPE_ID => NumericConstant::I8(*value as i8),
```
Comment (linusg) [inline src/typechecker.rs:458]: Likewise, and might need a conditional based on `c_int`'s actual size

Comment (HectorPeeters) [reply src/typechecker.rs]: I changed this one to work with the amount of bits and the signedness of the value instead of the individual types. This does not add any additional logic for the cchar, cint, and usize types.

File: src/typechecker.rs [hunk 3]
```diff
@@ -50,9 +51,38 @@ pub fn is_integer(type_id: TypeId) -> bool {
     }
 }
 
+pub fn is_signed(type_id: TypeId) -> bool {
+    match type_id {
+        USIZE_TYPE_ID | U8_TYPE_ID | U16_TYPE_ID | U32_TYPE_ID | U64_TYPE_ID => false,
```
Comment (linusg) [inline src/typechecker.rs:56]: This is not sufficient:

> https://doc.rust-lang.org/std/os/raw/type.c_char.html
> On modern architectures this type will always be either `i8` or `u8`, as they use byte-addresses memory with 8-bit bytes.

so we need to check for that.

**Review by linusg — CHANGES_REQUESTED** [review]

File: src/typechecker.rs (hunk 3 above)
Comment (HectorPeeters) [reply src/typechecker.rs:56]: That is indeed a good point. From what I can see in the documentation, it looks like the only way to check if c_char is signed is by checking if `c_char::MIN` is smaller than zero. This seems like a hacky solution but I don't see another way to check for that.

**Review by linusg — COMMENTED** [review]
LGTM now, thanks! Can you clean up the commit history a bit and squash the first, third and fourth commit into one? We don't need to preserve these iterations once merged :)
