### PR TITLE
Fix infinite loop while parsing illegal function call arguments

### LINKED ISSUE #155: Parser hangs infinitely on unclosed brackets in statements
```
function main() {
    println("test"
}
```

Trace output:

```
...
parse_file
parse_function: Token { contents: Name("function"), span: Span { file_id: 1, start: 2, end: 10 } }
parse_block: Token { contents: LCurly, span: Span { file_id: 1, start: 18, end: 19 } }
parse_statement: Token { contents: Name("println"), span: Span { file_id: 1, start: 24, end: 31 } }
parsing expression from statement parser
parse_expression: Token { contents: Name("println"), span: Span { file_id: 1, start: 24, end: 31 } }
parse_operand: Token { contents: Name("println"), span: Span { file_id: 1, start: 24, end: 31 } }
parse_call: Token { contents: Name("println"), span: Span { file_id: 1, start: 24, end: 31 } }
parse_expression: Token { contents: QuotedString("test"), span: Span { file_id: 1, start: 32, end: 38 } }
parse_operand: Token { contents: QuotedString("test"), span: Span { file_id: 1, start: 32, end: 38 } }
...
parse_expression: Token { contents: RCurly, span: Span { file_id: 1, start: 39, end: 40 } }
parse_operand: Token { contents: RCurly, span: Span { file_id: 1, start: 39, end: 40 } }
ERROR: unsupported expression
parse_operator: Token { contents: RCurly, span: Span { file_id: 1, start: 39, end: 40 } }
ERROR: unsupported operator (possibly just the end of an expression)
...
```

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
When the parser tries to parse an expression from "}" (for the second argument of the function), it errors out and doesn't increment the token index. But because the inner loop that repeatedly parses function parameter expressions never considered errors, it would get stuck in an infinite loop failing to parse "}".

The solution is simply to check for errors and bail out of the loop if there is one. A regression test has been added to the parser tests.

Fixes #155

### CODE REVIEW

File: src/parser.rs [hunk 1]
```diff
@@ -3898,6 +3898,12 @@ pub fn parse_call(tokens: &[Token], index: &mut usize) -> (Call, Option<JaktErro
                             index,
                             ExpressionKind::ExpressionWithoutAssignment,
                         );
+
+                        if let Some(jakt_error) = &err {
```
Comment (alimpfard) [inline src/parser.rs:3902]: How about checking if the index is changed instead?

Comment (kleinesfilmroellchen) [reply src/parser.rs:3902]: Well, it might be perfectly fine to not increment the index sometimes? Either way I think it's more generic to handle the sudden appearance of an error, no matter the reason.

File: tests/parser/unclosed-paren-in-function.jakt [hunk 2]
```diff
@@ -0,0 +1,7 @@
+// When the parser tries to parse an expression from "}" (for the second argument of the function),
+// it errors out and doesn't increment the token index.
+// But because the inner loop that repeatedly parses function parameter expressions never considered errors,
+// it would get stuck in an infinite loop failing to parse "}".
+function main() {
```
Comment (jntrnr) [inline tests/parser/unclosed-paren-in-function.jakt:5]: how is this test run?

Comment (jntrnr) [reply tests/parser/unclosed-paren-in-function.jakt:5]: Oops, I see it now. I missed we added other directories earlier

File: src/parser.rs [hunk 3]
```diff
@@ -3898,6 +3898,14 @@ pub fn parse_call(tokens: &[Token], index: &mut usize) -> (Call, Option<JaktErro
...
```
Comment (jntrnr) [inline src/parser.rs:3902]: we probably want to fix the warnings for `jakt_error` not being used. Guessing this should be passed along to `error`?

Comment (kleinesfilmroellchen) [reply src/parser.rs:3902]: Ah yes, sorry. I'm using rust-analyzer which doesn't give me Clippy warnings atm. I think I'll make an if-else out of this and just move err.

**Comment by jntrnr** [comment]
thanks!
